### ISSUE TITLE
Every time I start an web app, where I have AnimatedSplash as a Splash screen, I get an error.

### ISSUE THREAD

**Issue by rednikisfun** [fayaz07/animated_splash#16]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

• No issues found!

**This is the error:**

The following assertion was thrown while finalizing the widget tree:
_AnimatedSplashState#c4b49(ticker active but muted) was disposed with an active Ticker.

_AnimatedSplashState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: Ticker(created by _AnimatedSplashState#c4b49(lifecycle state: created))
The stack trace when the Ticker was actually created was:

 **Here in between, a great amount of links to different files like : " packages/flutter/src/scheduler/ticker.dart , packages/flutter/src/animation/animation_controller.dart, packages/flutter/src/widgets/framework.dart"*

As I understand, the main lines causing error are:

packages/flutter/src/scheduler/ticker.dart 67:40                                                                      <fn>
packages/flutter/src/scheduler/ticker.dart 68:14                                                                      new
packages/flutter/src/widgets/ticker_provider.dart 129:15                                                              createTicker
packages/flutter/src/animation/animation_controller.dart 247:20                                                       new
packages/animated_splash/animated_splash.dart 49:32   

Error: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
    at Object.throw_ [as throw] (http://localhost:52766/dart_sdk.js:4354:11)
    at http://localhost:52766/packages/flutter/src/widgets/widget_span.dart.lib.js:24929:21
    at framework.StatefulElement.new.[_debugCheckStateIsActiveForAncestorLookup] (http://localhost:52766/packages/flutter/src/widgets/widget_span.dart.lib.js:24932:23)
    at framework.StatefulElement.new.findAncestorStateOfType (http://localhost:52766/packages/flutter/src/widgets/widget_span.dart.lib.js:25021:69)
    at Function.of (http://localhost:52766/packages/flutter/src/widgets/widget_span.dart.lib.js:21262:63)
    at http://localhost:52766/packages/animated_splash/animated_splash.dart.lib.js:328:29
    at _RootZone.runUnary (http://localhost:52766/dart_sdk.js:37854:58)
    at _FutureListener.then.handleValue (http://localhost:52766/dart_sdk.js:32815:29)
    at handleValueCallback (http://localhost:52766/dart_sdk.js:33363:49)
    at Function._propagateToListeners (http://localhost:52766/dart_sdk.js:33401:17)
    at _Future.new.[_complete] (http://localhost:52766/dart_sdk.js:33234:25)
    at http://localhost:52766/dart_sdk.js:32381:30
    at internalCallback (http://localhost:52766/dart_sdk.js:24144:11)

**Comment by rednikisfun** [comment]
Is there anyone who can help me with the issue?
